# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c numba -c rapidsai -c pytorch
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ.get('CONDA_PY', 38) %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}

package:
  name: raft-dask
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python x.x
    - setuptools
    - cython>=0.29,<0.30
    - scikit-build>=0.13.1
    - rmm {{ minor_version }}
    - pylibraft {{ version }}
    - cudatoolkit {{ cuda_version }}.*
    - cuda-python >=11.7.1,<12.0
    - nccl>=2.9.9
    - ucx {{ ucx_version }}
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
  run:
    - python x.x
    - dask-cuda {{ minor_version }}
    - pylibraft {{ version }}
    - nccl>=2.9.9
    - rmm {{ minor_version }}
    - ucx >={{ ucx_version }}
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - dask>=2022.12.0
    - distributed>=2022.12.0
    - cuda-python >=11.7.1,<12.0
    - joblib >=0.11
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}

tests:                                 # [linux64]
  requirements:                        # [linux64]
    - cudatoolkit {{ cuda_version }}.* # [linux64]
  imports:                             # [linux64]
    - raft_dask                        # [linux64]

about:
  home: https://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: raft-dask library
