# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/raft/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/raft/labels

python:
  - changed-files:
      any-glob-to-any-file:
        - 'python/**'
cpp:
  - changed-files:
      any-glob-to-any-file:
        - 'cpp/**'
CMake:
  - changed-files:
      any-glob-to-any-file:
        - '**/CMakeLists.txt'
        - '**/cmake/**'
ci:
  - changed-files:
      any-glob-to-any-file:
        - 'ci/**'
