# Copyright (c) 2022-2023, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai
{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: raft-ann-bench
  version: {{ version }}
  script: build.sh

source:
  path: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - RAPIDS_ARTIFACTS_DIR
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libraft-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libraft-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  ignore_run_exports_from:
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }}
    {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} ={{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - cmake {{ cmake_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}

  host:
    - python
    - libraft {{ version }}
    - cuda-version ={{ cuda_version }}
    {% if cuda_major == "11" %}
    - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
    - libcublas {{ cuda11_libcublas_host_version }}
    - libcublas-dev {{ cuda11_libcublas_host_version }}
    {% else %}
    - cuda-profiler-api
    - libcublas-dev
    {% endif %}
    - glog {{ glog_version }}
    - nlohmann_json {{ nlohmann_json_version }}
    - h5py {{ h5py_version }}
    - benchmark
    - matplotlib
    - python
    - pandas
    - pyyaml
    # rmm is needed to determine if package is gpu-enabled
    - rmm ={{ minor_version }}

  run:
    - python
    - libraft {{ version }}
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    {% if cuda_major == "11" %}
    - cudatoolkit
    {% endif %}
    - glog {{ glog_version }}
    - h5py {{ h5py_version }}
    - benchmark
    - glog {{ glog_version }}
    - matplotlib
    - python
    - pandas
    - pyyaml
    # rmm is needed to determine if package is gpu-enabled
    - rmm ={{ minor_version }}
about:
  home: https://rapids.ai/
  license: Apache-2.0
  summary: RAFT ANN GPU and CPU benchmarks
