# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set ucx_py_version=environ.get('UCX_PY_VERSION') %}
package:
  name: libraft-nn
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libraft-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libraft-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768

requirements:
  build:
    - cmake>=3.20.1,!=3.23.0
  host:
    - libraft-headers {{ version }}
    - cudatoolkit {{ cuda_version }}.*
    - lapack
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda
    - gtest=1.10.0
    - gmock
    - librmm {{ minor_version }}
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}
    - libraft-headers {{ version }}
    - faiss-proc=*=cuda
    - libfaiss 1.7.0 *_cuda
    - libcusolver>=11.2.1
    - librmm {{ minor_version }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: libraft-nn library
