# Copyright (c) 2022-2023, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai
{% set version = environ.get('RAPIDS_PACKAGE_VERSION', '0.0.0.dev').strip('"').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libraft-split

source:
  path: ../../..

outputs:
  - name: libraft-headers-only
    version: {{ version }}
    script: build_libraft_headers.sh
    build:
      script_env: &script_env
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
        - CMAKE_C_COMPILER_LAUNCHER
        - CMAKE_CUDA_COMPILER_LAUNCHER
        - CMAKE_CXX_COMPILER_LAUNCHER
        - CMAKE_GENERATOR
        - PARALLEL_LEVEL
        - RAPIDS_ARTIFACTS_DIR
        - SCCACHE_BUCKET
        - SCCACHE_IDLE_TIMEOUT
        - SCCACHE_REGION
        - SCCACHE_S3_KEY_PREFIX=libraft-aarch64 # [aarch64]
        - SCCACHE_S3_KEY_PREFIX=libraft-linux64 # [linux64]
        - SCCACHE_S3_USE_SSL
        - SCCACHE_S3_NO_CREDENTIALS
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
        - librmm
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        {% if cuda_major != "11" %}
        - cuda-cudart-dev
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - librmm ={{ minor_version }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% endif %}
        - librmm ={{ minor_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft-headers-only library
  - name: libraft-headers
    version: {{ version }}
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
        - librmm
    requirements:
      host:
        - cuda-version ={{ cuda_version }}
      run:
        - {{ pin_subpackage('libraft-headers-only', exact=True) }}
        - librmm ={{ minor_version }}
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - libcublas {{ cuda11_libcublas_run_version }}
        - libcublas-dev {{ cuda11_libcublas_run_version }}
        - libcurand {{ cuda11_libcurand_run_version }}
        - libcurand-dev {{ cuda11_libcurand_run_version }}
        - libcusolver {{ cuda11_libcusolver_run_version }}
        - libcusolver-dev {{ cuda11_libcusolver_run_version }}
        - libcusparse {{ cuda11_libcusparse_run_version }}
        - libcusparse-dev {{ cuda11_libcusparse_run_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft-headers library
  - name: libraft
    version: {{ version }}
    script: build_libraft.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft library
  - name: libraft-static
    version: {{ version }}
    script: build_libraft_static.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft static library
  - name: libraft-tests
    version: {{ version }}
    script: build_libraft_tests.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libraft', exact=True) }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% endif %}
        - {{ pin_subpackage('libraft', exact=True) }}
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft tests
  - name: libraft-template
    version: {{ version }}
    script: build_libraft_template.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libraft', exact=True) }}
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        {% else %}
        - cuda-profiler-api
        - libcublas-dev
        {% endif %}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% endif %}
        - {{ pin_subpackage('libraft', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft template
