# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'
  linux64: ${{ linux and x86_64 }}

recipe:
  name: libraft-split

cache:
  source:
    path: ../../..

  build:
    script:
      content: |

        # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
        # incrementing version number in the compile line doesn't break the
        # cache
        set -x
        export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        set +x

        ./build.sh libraft tests --allgpuarch --compile-lib --compile-static-lib --no-nvtx -n

      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
        RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
        SCCACHE_S3_KEY_PREFIX: libraft/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
  requirements:
    build:
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }}
      - cuda-version =${{ cuda_version }}
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ stdlib("c") }}
    host:
      - cuda-version =${{ cuda_version }}
      - cuda-cudart-dev
      - cuda-profiler-api
      - libcublas-dev
      - libcurand-dev
      - libcusolver-dev
      - libcusparse-dev
      - librmm =${{ minor_version }}
      - nccl ${{ nccl_version }}
      - rapids-logger =0.2
      - ucxx ${{ ucxx_version }}

outputs:
  - package:
      name: libraft-headers-only
      version: ${{ version }}
    build:
      script:
        content: |
          # Unspecified brings in cuco and cutlass and friends
          cmake --install cpp/build --component Unspecified
          cmake --install cpp/build --component cuco
          cmake --install cpp/build --component raft
          cmake --install cpp/build --component distributed
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ compiler("c") }}
      host:
        - cuda-version =${{ cuda_version }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - rapids-logger =0.2
        - ucxx ${{ ucxx_version }}
        - cuda-cudart-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - librmm =${{ minor_version }}
        - rapids-logger =0.2
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ compiler("cxx") }}
          - ${{ compiler("cuda") }}
          - ${{ stdlib("c") }}
        by_name:
          - cuda-cudart
          - cuda-version
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - nccl
          - ucxx
    about:
      homepage: ${{ load_from_file("python/libraft/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libraft/pyproject.toml").project.license.text }}
      summary: libraft-headers-only library

  - package:
      name: libraft-headers
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
    requirements:
      host:
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - ucxx ${{ ucxx_version }}
        - cuda-version =${{ cuda_version }}
      run:
        - ${{ pin_subpackage("libraft-headers-only", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - ucxx ${{ ucxx_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ compiler("cxx") }}
          - ${{ compiler("cuda") }}
          - ${{ stdlib("c") }}
        by_name:
          - cuda-version
          - libmm
          - cuda-cudart
          - libcusparse
          - libcublas
          - libcurand
          - libcusolver
          - librmm
          - nccl
          - ucxx

    about:
      homepage: ${{ load_from_file("python/libraft/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libraft/pyproject.toml").project.license.text }}
      summary: libraft-headers library

  - package:
      name: libraft
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      script:
        content: |
          cmake --install cpp/build --component compiled
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ compiler("c") }}
      host:
        - ${{ pin_subpackage("libraft-headers", exact=True) }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
      run:
        - ${{ pin_subpackage("libraft-headers", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - cuda-profiler-api
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ compiler("cxx") }}
          - ${{ compiler("cuda") }}
          - ${{ stdlib("c") }}
        by_name:
          - cuda-version
          - libmm
          - cuda-cudart
          - libcusparse
          - libcublas
          - libcurand
          - libcusolver
          - librmm
          - nccl
          - ucxx
    about:
      homepage: ${{ load_from_file("python/libraft/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libraft/pyproject.toml").project.license.text }}
      summary: ${{ load_from_file("python/libraft/pyproject.toml").project.description }}

  - package:
      name: libraft-static
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      script:
        content: |
          cmake --install cpp/build --component compiled-static
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ compiler("c") }}
      host:
        - ${{ pin_subpackage("libraft-headers", exact=True) }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
      run:
        - ${{ pin_subpackage("libraft-headers", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - cuda-profiler-api
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ compiler("cxx") }}
          - ${{ compiler("cuda") }}
          - ${{ stdlib("c") }}
        by_name:
          - cuda-version
          - libmm
          - cuda-cudart
          - libcusparse
          - libcublas
          - libcurand
          - libcusolver
          - librmm
          - nccl
          - ucxx
    about:
      homepage: ${{ load_from_file("python/libraft/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libraft/pyproject.toml").project.license.text }}
      summary: libraft static library

  - package:
      name: libraft-tests
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      script:
        content: |
          cmake --install cpp/build --component testing
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage('libraft', exact=True) }}
        - ${{ pin_subpackage('libraft-static', exact=True) }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
      run:
        - ${{ pin_subpackage("libraft", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
      ignore_run_exports:
        from_package:
          - ${{ compiler("c") }}
          - ${{ compiler("cxx") }}
          - ${{ compiler("cuda") }}
          - ${{ stdlib("c") }}
        by_name:
          - cuda-version
          - libmm
          - cuda-cudart
          - libcusparse
          - libcublas
          - libcurand
          - libcusolver
          - librmm
          - nccl
          - ucxx
    about:
      homepage: ${{ load_from_file("python/libraft/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libraft/pyproject.toml").project.license.text }}
      summary: libraft tests
