c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake_version:
  - ">=3.26.4,!=3.30.0"
