
/*
 * SPDX-FileCopyrightText: Copyright (c) 2023, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by 00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python 00_generate.py
 *
 */

#include <raft/distance/fused_l2_nn.cuh>
