name: RAFT wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

jobs:
  pyraft:
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-wheels.yml@feat/wheel-ci-actions
    with:
      package-name: raft
      package-dir: python/raft
      cibw-before-all: "dnf install -y blas blas-devel lapack lapack-devel"
      cibw-before-build: "pip install rmm-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      skbuild-configure-options: '-DRAFT_COMPILE_LIBRARIES=ON -DRAFT_EXCLUDE_FAISS_FROM_ALL=OFF -DRAFT_USE_FAISS_STATIC=OFF -DRAFT_COMPILE_NN_LIBRARY=ON -DRAFT_COMPILE_DIST_LIBRARY=ON -DBUILD_TESTS=OFF'
      cpu-smoketest-command: "python3 -c 'import raft; print(raft)'"
      gpu-smoketest-command: ""
    secrets: inherit
  pylibraft:
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-wheels.yml@feat/wheel-ci-actions
    with:
      package-name: pylibraft
      package-dir: python/pylibraft
      cibw-before-all: "dnf install -y blas blas-devel lapack lapack-devel"
      cibw-before-build: "pip install rmm-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      skbuild-configure-options: '-DRAFT_COMPILE_LIBRARIES=ON -DRAFT_EXCLUDE_FAISS_FROM_ALL=OFF -DRAFT_USE_FAISS_STATIC=OFF -DRAFT_COMPILE_NN_LIBRARY=ON -DRAFT_COMPILE_DIST_LIBRARY=ON -DBUILD_TESTS=OFF'
      cpu-smoketest-command: "python3 -c 'import pylibraft; print(pylibraft)'"
      gpu-smoketest-command: ""
    secrets: inherit
